### ISSUE TITLE
offline ?

### ISSUE THREAD

**Issue by pranavlathigara** [xuuhaoo/OkSocket#1]
Hi Thanx for this library.
can i use this lib for internal chat or data transferring like xender (Wifi socket Connection Client-Server)?

**Comment by xuuhaoo** [comment]
First I'm really sorry for this document not in English.
This library just care about Server IP and Server Port.So just base on this condition is all fine.

**Comment by xuuhaoo** [comment]
@pranavlathigara 
First I'm really sorry for this document not in English.
This library just care about Server IP and Server Port.So just base on this condition is all fine.

**Comment by xuuhaoo** [comment]
@pranavlathigara You can add my WeChat :xuuhaoo

**Comment by pranavlathigara** [comment]
@xuuhaoo OK

**Comment by showbestriven** [comment]
could i add your WeChat too ? I also want to ask you some question!

**Comment by xuuhaoo** [comment]
@showbestriven Sure,Let me know what question you have~

**Comment by showbestriven** [comment]
@xuuhaoo Has you loved Chen Hu?

**Comment by xuuhaoo** [comment]
@showbestriven 你可以用中文和我交流....
