### ISSUE TITLE
异常断开:com.xuhao.android.libsocket.impl.exceptions.ReadException: we can't read data bigger than 10Mb,cause=com.xuhao.android.libsocket.impl.exceptions.ReadException: we can't read data bigger than 10Mb

### ISSUE THREAD

**Issue by zjsa** [xuuhaoo/OkSocket#10]
往服务端发送一个json数据，接收服务端返回的数据报了这个错误。。。！异常断开:com.xuhao.android.libsocket.impl.exceptions.ReadException: we can't read data bigger than 10Mb,cause=com.xuhao.android.libsocket.impl.exceptions.ReadException: we can't read data bigger than 10Mb

**Comment by xuuhaoo** [comment]
原因是服务器没有按照标准协议返回
![image](https://user-images.githubusercontent.com/10423664/32480364-5fac2ce2-c3c9-11e7-8d73-8163138813a0.png)
