### ISSUE TITLE
心跳包时间不准，误差有点大，间隔2分钟左右的话 误差有几十秒

### ISSUE THREAD

**Issue by StephenGiant** [xuuhaoo/OkSocket#102]
ConnectionInfo connectionInfo = new ConnectionInfo(HOST, PORT);
        OkSocketOptions.Builder builder = new OkSocketOptions.Builder();
        //设置头的格式
        builder.setHeaderProtocol(new IHeaderProtocol() {
            @Override
            public int getHeaderLength() {
                return 10; //头数据固定是10
            }

            @Override
            public int getBodyLength(byte[] header, ByteOrder byteOrder) {
                byte[] bytes = new byte[4];
                System.arraycopy(header, 2, bytes, 2, 2);
                int length = UnpackTool.byteArrayToInt(bytes);//数据的长度
                return length - 10;
            }
        });
        builder.setPulseFrequency(1000 * 150);//设置心跳的间隔
        builder.setWritePackageBytes(1460);
        manager = OkSocket.open(connectionInfo).option(builder.build());
        manager.registerReceiver(actionAdapter);
        if (!manager.isConnect()) {
            manager.connect();//连接
        }

**Comment by xuuhaoo** [comment]
什么手机版本,什么场景下有不准误差

**Comment by StephenGiant** [comment]
最新版本，手机7.0系统，锤子坚果

**Comment by xuuhaoo** [comment]
We are already locating the problem which to cause the heartbeat time inaccuracy.
Because the Handler Looper is too busy to do the timing job.
We'll change the way to timing rather than to use the Handler.postDelay().
Please looking forward new version to support you better heartbeat experience
