### ISSUE TITLE
请问有能 将java对象中每一属性转换成 Byte，然后组装成一个Byte[],然后又能反向解析的库不？

### ISSUE THREAD

**Issue by bananaCaptain** [xuuhaoo/OkSocket#106]
1.如题目，请问作者有遇见过这样的库不？
将java对象中每一属性转换成 Byte或者Byte[]，然后组装成一个Byte[],然后又能反向解析的库不？就好像Gson将 java对象与json互转一样。麻烦了

**Comment by xuuhaoo** [comment]
自己写一个吧....不是很难
