### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by debpedrano** [xuuhaoo/OkSocket#107]
Greetings!

This might be a great opportunity to tell you that I am offering logo designs for GitHub projects. And it would be an honor to offer this to you if you wanted me to do so, just mention me. Thanks!

**Comment by xuuhaoo** [comment]
Thanks for your offering. But I don't need it for now. Thinks again.

**Comment by debpedrano** [comment]
Do you have a small description of OKsocket wikis? or maybe put some an idea about your perspective output of the logo?
@xuuhaoo

**Comment by xuuhaoo** [comment]
OkSocket is a Java library project designed to solve lightweight Socket communication, in order to enable developers to focus more on business logic, rather than TCP communication principles and some protocols. Make Socket communication more beautiful, suitable for large, medium and small Project, the rapid development of stable, maintainable, reliable Socket connection.

About logo, in my opinion, maybe more cheerful, sunny, professional, and not too complicated. People can remember at a glance

**Comment by debpedrano** [comment]
I already have an idea, I hope you will like it. Ill comment it here soon

**Comment by debpedrano** [comment]
I dunno if I made it right, I made two designs

![image](https://user-images.githubusercontent.com/40510200/48345606-68684b00-e6b3-11e8-8696-fd75dd3cf440.png)

**Comment by debpedrano** [comment]
I also have a design to be presented later, don't worry. Ill make a bunch of it :)

**Comment by xuuhaoo** [comment]
Wow, it's fantastic. And I have a question about the logo.
![image](https://user-images.githubusercontent.com/10423664/48390185-b45ed280-e73b-11e8-8977-c9aa693eeacb.png)
What does that logo mean in your design?

**Comment by xuuhaoo** [comment]
I am very grateful for your contribution. And looking forward to your design.

**Comment by debpedrano** [comment]
@xuuhaoo 

How about this one? 
![image](https://user-images.githubusercontent.com/40510200/48427963-f7a15b80-e7a4-11e8-9120-581a1d6e2449.png)

**Comment by xuuhaoo** [comment]
This version of a lot better. Thank you for your contribution, but I think there are some areas that can be improved. For example, can the overall logo be slightly wider?

**Comment by debpedrano** [comment]
How about this one @xuuhaoo 

![image](https://user-images.githubusercontent.com/40510200/48660673-84e3f900-eaa0-11e8-9e79-93817125753d.png)

**Comment by debpedrano** [comment]
if you have any color ideas, please tell me. So that I can have that variations.

**Comment by xuuhaoo** [comment]
Could you provide this one png part by part
![image](https://user-images.githubusercontent.com/10423664/48830042-a00b7d00-edae-11e8-9714-06837638c74f.png)

**Comment by debpedrano** [comment]
sorry for responding late @xuuhaoo , ill be starting making your request. Have a nice day!
