### ISSUE TITLE
请问能设置客户端接收数据的端口不？

### ISSUE THREAD

**Issue by bananaCaptain** [xuuhaoo/OkSocket#109]
作者你好！如题!
请问能设置客户端接收数据的端口不？
麻烦了

**Comment by cnkker** [comment]
源码里面有

**Comment by bananaCaptain** [comment]
@cnkker 请问具体源码的位置在哪里?客户端的监听端口能设置不?麻烦了

**Comment by xuuhaoo** [comment]
本地端口是吗

**Comment by bananaCaptain** [comment]
@xuuhaoo 作者你好!是的!
暂时找到了实现 OkSocketFactory这个对象来自己创建 Socket 实现,这样做会提示不能在主线程创建,只能另外起线程了.
不知道能不能再简单点直接设置就可以了.或者有时候不是需要设置本地接收数据端口,只是想查一下本地接收数据端口.
感谢作者!

**Comment by xuuhaoo** [comment]
好的...下一个版本支持

**Comment by xuuhaoo** [comment]
端口支持已经加好了...您可以加群,我给你出一个内侧版本.

**Comment by bananaCaptain** [comment]
@xuuhaoo 作者你好!我加入QQ群了!请问怎样找你!真的感谢了
