### ISSUE TITLE
Read Ip Camera Stream

### ISSUE THREAD

**Issue by kadircanerergun** [xuuhaoo/OkSocket#110]
Hi, I have an ip camera it gives jpeg when i browse with browser. I need to write a socket that connect to camera and receive images continuously. Is there any example ?

**Comment by xuuhaoo** [comment]
Hi, there is a demo app in the project. Maybe you can clone the project and just run it in AndroidStudio.
The demo has the English language. 
About your requirements, I guess you can serialize jpeg to byte arrays and transfer it through the socket to the server, and this as same as IM. If you have any questions, you can let me know, and very happy to help you.

**Comment by xuuhaoo** [comment]
### There is an example I wrote, my ears are open.
my suggestions:
- 1. First you need defined structure about Jpeg like this:
```java
public class Jpeg implements ISendable {

    private static final int HEADER_BYTE_LENGTH = 4;

    private Bitmap mBitmap;

    public Jpeg(Bitmap bitmap) {
        mBitmap = bitmap;
    }

    @Override
    public byte[] parse() {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        mBitmap.compress(Bitmap.CompressFormat.JPEG, 100, baos);
        byte[] imgArrs = baos.toByteArray();
        ByteBuffer bb = ByteBuffer.allocate(HEADER_BYTE_LENGTH + imgArrs.length);
        bb.order(ByteOrder.BIG_ENDIAN);
        bb.putInt(imgArrs.length);
        bb.put(imgArrs);
        return bb.array();
    }
}
```
- 2. Next you just need to send it.
```java
    Bitmap bitmap = null/*ignore null I wrote, there should put the bitmap you got*/;
    Jpeg jpeg = new Jpeg(bitmap);
    mManager.send(jpeg);
    bitmap.recycle();
```

**Comment by kadircanerergun** [comment]
Thank you very much @xuuhaoo but i need opposite of this. Camera gives jpegs when i browse it with web browser like 192.168.43.143:7060. When i refresh page jpeg changes. Now i want to read with socket and change imageview with this images.

**Comment by xuuhaoo** [comment]
Opps~ I understand what you need to do.
* You already got an IP Camera device, and it provides a way for a browser to browse. 
* You need to know is whether the camera provides a socket connection for you to use.
* If there isn't socket connection for you, maybe you can use an old way, such as make a Get request to `192.168.43.143:7060` and parsing the response you got. 
* Or you can try to connect `192.168.43.143:7060` by the oksocket, and find what you got.

**Comment by xuuhaoo** [comment]
Because in your description as above, you send a Get request in the browser, and you got an Image. Now you just need send a Get request in your android phone, I guess you will also get an Image. You can start an `IntentThread` and to send Get request by Okhttp, put the result in your imageview.

**Comment by kadircanerergun** [comment]
Hi @xuuhaoo. Thanks for respone. I have a native cpp library that doing the job i need. If i send source to you can it help us for solve this problem ?
