### ISSUE TITLE
刚连接上紧跟着就断开链接

### ISSUE THREAD

**Issue by futurelc** [xuuhaoo/OkSocket#111]
刚才测试大佬的库，发现链接socket后在onClientConnected 方法内调用client.addIOCallback(activity);立刻会走到onClientDisconnected方法，不知道为何？

**Comment by xuuhaoo** [comment]
这样很难判断问题,请详细说明

**Comment by JYungSiu** [comment]
遇到同样问题；服务端看到连接上来就立刻断开，客户端报：java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer) ，并disconnected ，排查了很久都没找到原因，头痛中。

**Comment by xuuhaoo** [comment]
Connection reset by peer 一般是由于网络原因导致的

**Comment by sceneren** [comment]
我也是这个问题  每次都是连上就断开 有啥办法没
