### ISSUE TITLE
你好，server端收不到消息，一收消息连接就断开？(Android4.4)

### ISSUE THREAD

**Issue by tonytangcn** [xuuhaoo/OkSocket#114]
我用了两个Android4.4的设备都这样，client发消息后server直接进入onClientDisconnected。gitclone你的项目在我的Android设备上debug一样遇到这个问题。目前还没在其他Android版本上测试过。谢谢

**Comment by xuuhaoo** [comment]
打开oksocket的debug功能,把日志拿出来

**Comment by Joinfeng** [comment]
>>>
onSocketDisconnection: action_disconnection:Exception:com.xuhao.didi.core.exceptions.ReadException: Need to follow the transmission protocol.
    Please check the client/server code.
    According to the packet header data in the transport protocol, the package length is 1130915171 Bytes.
    You need check your <ReaderProtocol> definition
<<<
也遇到这情况，估计是因为后台数据没有按照指定的数据结构发送数据，所以client解析不错来，造成的报错。

**Comment by xuuhaoo** [comment]
是的后台数据没有按照你们协定好的发送,具体接受数据格式看下文档,中文的在简书,英文的是WIKI 里面有关于如何接收数据
