### ISSUE TITLE
你好，请教下连接超时问题

### ISSUE THREAD

**Issue by h9581015** [xuuhaoo/OkSocket#115]
hi，作者你好请教个问题:
超时时间设置为60s(setConnectTimeoutSecond), 没有使用框架里面的重连机制(setReconnectionManager(new NoneReconnect()))情况下， 在弱网环境一直没有看到回调发生，请问是否碰到过类似问题，在registerReceiver注册接口里面是否有连接超时回调呢？

**Comment by xuuhaoo** [comment]
您需要先注册adapter再进行连接,肯定会有回调的,你可以把时间设置短一些再试试
