### ISSUE TITLE
一个手机开启服务一个手机当前端 连接不上

### ISSUE THREAD

**Issue by nuoyan2** [xuuhaoo/OkSocket#119]
一个手机开启服务 另一个手机当客户端 连接不上 用的是同一个wifi

**Comment by Mauiie** [comment]
我也遇到连接被拒的问题，同一个WIFI没有问题，同一个路由下的两个WIFI信号，ip在同一频段，互相可以ping通，但是连接被拒 java.net.ConnectException: Connection refused

**Comment by xuuhaoo** [comment]
确保在一个内网中,例如将两个手机连接同一个wifi,检查下wifi设置中不要有代理设置

**Comment by xuuhaoo** [comment]
使用新版本.问题得到解决
