### ISSUE TITLE
If body length is 0(only have header), then it's will fall into a dead loop.

### ISSUE THREAD

**Issue by leemoncn** [xuuhaoo/OkSocket#12]
It will invoke onSocketWriteResponse heaps of times.

**Comment by xuuhaoo** [comment]
I can't reproduce the problem ,as follow the pic
![image](https://user-images.githubusercontent.com/10423664/32734368-cf7d00f2-c8cc-11e7-9234-89a0710291a0.png)

**Comment by xuuhaoo** [comment]
You need check your data which returned by the server.The head of data is correct.

**Comment by xuuhaoo** [comment]
![image](https://user-images.githubusercontent.com/10423664/32734673-a6c9b226-c8cd-11e7-900e-bbae43b09e0e.png)
onSocketWriteResponse method will invoked once when you call send function.

**Comment by xuuhaoo** [comment]
You can download the demo apps for study how to use it to communicate with your server

**Comment by xuuhaoo** [comment]
@Jack-SunQi You mean you got a empty header? How could that happen.would you tell me the step of your issues reproducing exactly?

**Comment by leemoncn** [comment]
在Reader.java文件的read()方法，如果服务端关闭了socket，mInputStream.read()会读取到-1，但是现在并没有对-1进行处理，所以socket读取会进入死循环。

**Comment by leemoncn** [comment]
测试方法就是，服务器直接close socket，客户端这边就死循环了。

**Comment by leemoncn** [comment]
read head: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
need read body length: 0

**Comment by xuuhaoo** [comment]
谢谢反馈,即将定位问题解决

**Comment by xuuhaoo** [comment]
服务器应该清空Socket缓冲区,因为关闭后没有清空缓冲区.造成的读取ff ff ff情况.目测应该是C或者C++的Socket服务器才会出现此种情况,这种问题在于服务器的问题,请您服务器的同学这边处理下
