### ISSUE TITLE
client端能否添加一个接口直接返回获取到的service数据

### ISSUE THREAD

**Issue by Roc-egg** [xuuhaoo/OkSocket#120]
希望client端能添加一个接口直接返回获取到的service数据，可以不用配置setReaderProtocol，返回数据自己处理，谢谢.

**Comment by Endless-explorer** [comment]
同求

**Comment by xuuhaoo** [comment]
这个protocol就是给你们自己处理的接口.
必须符合报文头报文体的规则,其他的规则不支持
