### ISSUE TITLE
心跳包是否能每次不一样啊

### ISSUE THREAD

**Issue by HoLyBird** [xuuhaoo/OkSocket#121]
心跳包是否能每次不一样啊

**Comment by xuuhaoo** [comment]
直接修改心跳包bean的数据就可以了

**Comment by HoLyBird** [comment]
我在onSocketReadResponse里，ConnectionManager.getPulseManager().setPulseSendable(new MessageBean(x,y,z))，然后feed喂狗。xyz是实时变化不一样的值。这样可以发心跳包，但是发送的xyz每次是一样的。请问是心跳包不能这样发送吗?

**Comment by xuuhaoo** [comment]
MessageBean(x,y,z) 你把这个对象的引用拿到..之后传递这个引用到pulseManager,之后你修改这个引用就好了
