### ISSUE TITLE
How can i get body length by header(byte[])?

### ISSUE THREAD

**Issue by Jack-SunQi** [xuuhaoo/OkSocket#13]
i set header protocol on onCraete(), when the getBodyLength() is called, the length of header(byte[]) is always 0.

**Comment by xuuhaoo** [comment]
@Jack-SunQi Could you post your code on issues?

**Comment by xuuhaoo** [comment]
as follows the pic.Your getBodyLength() method is depend on the value which the getHeaderLength() method returned.
![image](https://user-images.githubusercontent.com/10423664/32765547-ec71bcb0-c945-11e7-965d-4a7ad1378879.png)

**Comment by Jack-SunQi** [comment]
![tim 20171114141013](https://user-images.githubusercontent.com/7379751/32765551-ee7ae298-c945-11e7-8be7-5d170981d432.png)

**Comment by xuuhaoo** [comment]
I can see you are Chinese .And either am I.Shall we communicate in Chinese?

**Comment by Jack-SunQi** [comment]
我看到你用的框架上header的长度默认为4， 但是我这边需要的长度是0， 所以我重新设置了headerProtocol， 在getHeaderLength方法中返回的value是0（这一步应该没错吧）， 然后我现在想知道getBodyLength这个方法的值应该怎么返回？

**Comment by xuuhaoo** [comment]
这个版本的 OkSocket 还不能支持包头为零的情况,因为 Socket 通讯中会出现粘包拆包问题,框架需要根据包头进行粘包拆包,所以,包头不能为零.服务器需要返回包头加包体.

**Comment by Jack-SunQi** [comment]
我看到另外一个问题也说到如果返回的headerLength和bodyLength都是0的话就会出现一个死循环，我这边也遇到，可能就是这个原因吧。thanks any way

**Comment by xuuhaoo** [comment]
会出现死循环...这是个很糟糕的问题,将在以后版本中解决

**Comment by xuuhaoo** [comment]
@Jack-SunQi 请问下,您是什么需求会有包头为零的时候,我们希望在下一版本中除了修复现有 bug 以外,还能够扩展下这个包头为零的场景,能否详细说明下您的使用需求

**Comment by Jack-SunQi** [comment]
我们现在在对接一款智能硬件，基于TCP，数据格式是以json格式发送，没有包头。对于粘包的问题，如果出现一次性发送多条数据是以\n分隔

**Comment by xuuhaoo** [comment]
好的,最新一版大概周六前会上线,届时版本号为1.2.0,您可以关注下,希望可以满足你的需求

**Comment by Jack-SunQi** [comment]
万分感谢

**Comment by hkllzh** [comment]
同样问题，我们最初的设计也是无包头的设计。希望修改一下。

**Comment by xuuhaoo** [comment]
@hkllzh 好的,周六前会发版本,届时版本号1.2.0.将会支持无包头设计

**Comment by wanggenyou** [comment]
@xuuhaoo 什么时候发布新版本？

**Comment by xuuhaoo** [comment]
@wanggenyou 正在开发测试

**Comment by Jack-SunQi** [comment]
1.2.0还没有发布嘛？

**Comment by xuuhaoo** [comment]
最近DIDI在筹划新版本.可能延期了.不好意思.具体时间会再定.

**Comment by xuuhaoo** [comment]
目前进度是开发了50%,会加上SSLSOCKET

**Comment by soul0932** [comment]
可以使用无包头的数据了吗

**Comment by xuuhaoo** [comment]
经过慎重考虑,决定框架不支持无包头设计,因为开发过程中,虽然已经实现了无包头设计,但这和当初设计框架之初的思想不符合,因此将代码进行了回退.具体的设计思想很简单,就是读取到您指定的一个结束符即认为这次包结束.Socket通讯中应该尽量避免使用readLine或者这种无包头设计,因为一旦读取不到结束符,会导致阻塞.因此如果各位需要无包头的支持,请下载代码自行修改
