### ISSUE TITLE
ConnectionManagerImpl#isConnect存在线程安全问题

### ISSUE THREAD

**Issue by addhaloka** [xuuhaoo/OkSocket#133]
Attempt to invoke virtual method 'boolean java.net.Socket.isClosed()' on a null object reference java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.net.Socket.isClosed()' on a null object reference at com.xuhao.didi.socket.client.impl.client.ConnectionManagerImpl.isConnect()

**Comment by xuuhaoo** [comment]
I have noticed the problem. This issue will be addressed in the next few releases

**Comment by addhaloka** [comment]
什么时候修复?
