### ISSUE TITLE
可以不使用header：ByteArray吗，通过头来计算body大小总会出一些问题。

### ISSUE THREAD

**Issue by IINI** [xuuhaoo/OkSocket#137]
可以不使用header：ByteArray吗，我服务器下发的数据都是字符串形式，在类型转换的时候有问题。比如说接受到单次数据就直接解析，而不是等待达到规定大小的body才输出给我

**Comment by LannyLee** [comment]
你说的没错，但是好像默认的按照四个字节解析了，我只想获取单次数据

**Comment by IINI** [comment]
现在服务端和客户端我都采用了使用4byte的头来构造了。服务端PHP用字节计算函数获取字符串byte数，再计算byte数的位数，不够补在前面0，然后和原始字符串拼接。客户端获取4byte。利用取出单byte*10^(n-1)来相加获取body字节数n是位数。

**Comment by IINI** [comment]
现在服务端和客户端我都采用了使用4byte的头来构造了。服务端PHP用字节计算函数获取字符串byte数，再计算byte数的位数，不够补在前面0，然后和原始字符串拼接。客户端获取4byte。利用取出单byte*10^(n-1)来相加获取body字节数n是位数。

**Comment by xuuhaoo** [comment]
通过头计算body大小是为了粘包拆包,这个是网络通讯规范中的惯用做法,例如IP协议,TCP协议等都是使用固定头和动态包体的做法
