### ISSUE TITLE
当数据比较大时toHexStringForLog这个方法似乎有些问题

### ISSUE THREAD

**Issue by hiperioncn** [xuuhaoo/OkSocket#14]
当数据比较大时toHexStringForLog（BytesUtils.java）这个方法似乎有些问题，我接收了一个图片，大概60k，这个方法处理完大概要2分钟。虽然只是为了打印log，但是这样影响后面继续接收数据。

**Comment by xuuhaoo** [comment]
可以在 Application 中初始化时将 isDebug 设置为 False, 后续会优化这个

**Comment by xuuhaoo** [comment]
另外,我不建议您一次性接收60k 的东西,很容易造成在低配手机上出现 oom, 我们是有分包机制的,您可以选择分为1024个字节为一个包的形式,进行拆包接收

**Comment by hiperioncn** [comment]
我提交了一个request, 更新了一下你的那个方法。

**Comment by xuuhaoo** [comment]
感谢,我看下

**Comment by hiperioncn** [comment]
还有个问题，重连时如何取消？让它停止重连

**Comment by hiperioncn** [comment]
okOptionsBuilder.setConnectionHolde()这里拼写错误，结尾少了一个n，应该是OkSocketOptions.java
中定义变量时就少了一个n，变量定义成了isConnectionHolde，导致自动生成get set方法时也少了一个n

**Comment by xuuhaoo** [comment]
你可以参考下 Demo中 SimpleMainActivity 中的处理,里面就有停止重连的方法

**Comment by xuuhaoo** [comment]
好的拼写错误会改正
