### ISSUE TITLE
同一IP和端口多次打开为同一通道

### ISSUE THREAD

**Issue by MaDengTT** [xuuhaoo/OkSocket#148]
OkScoket.open()方法多次连接同一IP和端口，服务器发现客户端连接IP和端口不变。是否有参数控制，让每次打开一个新的通道

**Comment by xuuhaoo** [comment]
每次是一个通道的朋友,当然,如果你需要每次都是新的通道有一个配置是让oksocket不保存通道实例,有一个hold的参数可以实现你的需求
