### ISSUE TITLE
OKsocket如何在多个activity中异步接收处理消息

### ISSUE THREAD

**Issue by IINI** [xuuhaoo/OkSocket#149]
我把OKsocket设成application类的一个对象了，多个activity共用一个实例。但是我获取异步消息的时候有些困难，我能直接在每个activity中重写Manger.adapter吗

**Comment by xuuhaoo** [comment]
可以..但是你要记得在每个activity销毁的时候反注册,否则将会永远在oksocket的连接管理器中

**Comment by IINI** [comment]
好的。我试试，多谢
