### ISSUE TITLE
连接地址后缀问题

### ISSUE THREAD

**Issue by hjzlzh123** [xuuhaoo/OkSocket#156]
你好，请问我现在的链接地址后面有一个后缀，例如：ws://locallhost:8080/api/webSocket，这种我该怎么去连接吗

**Comment by spianmo** [comment]
oksocket不能连websocket（ws）吧

**Comment by hjzlzh123** [comment]
嗯嗯明白了，谢谢，因为后台用的是websocket，所有需要换一个框架了

**Comment by xuuhaoo** [comment]
恩..推荐你使用okio
