### ISSUE TITLE
请问如何处理Read超时问题

### ISSUE THREAD

**Issue by hiperioncn** [xuuhaoo/OkSocket#16]
加入在通讯过程中数据丢包，或者服务器端发送的body数据短于header中定义的长度，造成inputstream.read()进入无限等待状态，我尝试mSocket.setSoTimeout(5000),但无法达到预想的效果，连接超过5秒后，连接自动断开了。我期望是每次执行read有一个超时时间可以设置，请问有什么好的解决方法？

**Comment by xuuhaoo** [comment]
首先, header 中的定义长度必须是真实的 body 长度,为什么会出现 header 定义的和实际 body 不相同.

**Comment by hiperioncn** [comment]
假设服务器端发送定义的header中body长度是真实的，但发送body数据过程中出现了错误，造成body长度不符

**Comment by xuuhaoo** [comment]
数据传输不会出现错误.如果不相符肯定是服务器业务逻辑出现问题.

**Comment by hiperioncn** [comment]
好的，多谢
