### ISSUE TITLE
如何自定义接收数据类型?

### ISSUE THREAD

**Issue by tydqcjj** [xuuhaoo/OkSocket#162]
OkSocket  接收数据不是框架定义的header+body的类型会报错，请问怎么解决？可以自定义接收类型吗?
![image](https://user-images.githubusercontent.com/21003314/71948250-609a2d00-320a-11ea-8714-28126a6a1f38.png)

**Comment by xuuhaoo** [comment]
可以自定义数据类型,你看下本仓库的WIKI中关于如何接收数据的连接
[关于如何自定义接收协议](https://github.com/xuuhaoo/OkSocket/wiki/Receiving-Protocol)

**Comment by tej-mpc** [comment]
okay. But please share how to send header and share formate or sample of header and payload which accept current code.
