### ISSUE TITLE
包体长度怎么解析？

### ISSUE THREAD

**Issue by flyjiang2014** [xuuhaoo/OkSocket#17]
@Override
    public int getBodyLength(byte[] header, ByteOrder byteOrder) {
    	//从header(包头数据)中解析出包体的长度,byteOrder是你在参配中配置的字节序,可以使用ByteBuffer比较方便解析
        return 0;
    }
这个包体长度到底怎么解析，能不能告知下方法，比如我现在 header 数据是 {0，1，0，1, 0，0，0，106}，后面4位表示包体的长度。

**Comment by xuuhaoo** [comment]
您的问题解决了吗

**Comment by flyjiang2014** [comment]
用了笨办法：
ByteBuffer bb = ByteBuffer.wrap(header);
bb.getShort();
bb.getShort();
int length = bb.getInt();
length就是包体长度

**Comment by StephenGiant** [comment]
我是先提取后4位，然后使用运算符转成int的
