### ISSUE TITLE
System.err: java.lang.IllegalArgumentException: The header length can not be zero.

### ISSUE THREAD

**Issue by Yumikolab** [xuuhaoo/OkSocket#175]
如果不需要头部，有解决的方法嘛？

**Comment by cyzaoj** [comment]
+1

**Comment by sunyaodong** [comment]
+1

**Comment by xuuhaoo** [comment]
暂时不支持没有包头的这种格式

**Comment by tej-mpc** [comment]
can you please say how to add header?. I am testing with PC software "herculas"(as client). I want to send message only "123456". please help how to add header for send message to mobile app (server)

![image](https://user-images.githubusercontent.com/84148978/129912484-ad4cbc03-9fd1-4e34-8a6d-4ee0753f07a8.png)
