### ISSUE TITLE
传输数据需要用证书加密，我想问下这个框架能实现功能吗？

### ISSUE THREAD

**Issue by flyjiang2014** [xuuhaoo/OkSocket#18]
传输数据需要用证书加密，我想问下这个框架能实现功能吗？是使用的SSLSocket

**Comment by xuuhaoo** [comment]
这个之后会在后续版本中考虑.之前设计的时候有考虑但是目前不支持

**Comment by xuuhaoo** [comment]
已经支持,请您依赖1.2.0版本的OkSocket库
