### ISSUE TITLE
我想实现断线重连，应该在什么地方加上重连的代码呢

### ISSUE THREAD

**Issue by yangyingdong** [xuuhaoo/OkSocket#180]
我想实现断线重连，应该在什么地方加上重连的代码呢

**Comment by luomo1301532** [comment]
OkSocketOptions.Builder builder = new OkSocketOptions.Builder();
        builder.setReconnectionManager(OkSocketOptions.getDefault().getReconnectionManager());这样就可以断线重连了

**Comment by xuuhaoo** [comment]
> OkSocketOptions.Builder builder = new OkSocketOptions.Builder();
> builder.setReconnectionManager(OkSocketOptions.getDefault().getReconnectionManager());这样就可以断线重连了

正解
