### ISSUE TITLE
建议加入header的检查和下跳

### ISSUE THREAD

**Issue by mothz** [xuuhaoo/OkSocket#19]
建议在自定义协议中加入头部数据的检查，能在getbodylength前处理，丢弃或保留header的部分数据(header中可能未读取或者已包含了body的数据)，如果不做容错处理，若对方因干扰传入了不符合协议的数据后面读取就乱套了。

**Comment by xuuhaoo** [comment]
在读取时有容错处理,如果出现错误,会断开重连

**Comment by mygod3904** [comment]
断开重连的操作是需要自己来写吗？
