### ISSUE TITLE
你好,麻烦看一下

### ISSUE THREAD

**Issue by zhouke23** [xuuhaoo/OkSocket#20]
com.xuhao.android.libsocket.impl.exceptions.ReadException: we can't read data bigger than 10Mb,cause=com.xuhao.android.libsocket.impl.exceptions.ReadException: we can't read data bigger than 10Mb

这个问题 我发现 跟 那个 BIG_ENDIAN  和 LITTLE_ENDIAN 有关系,这个东西高低字节有点不太好理解!
而且 我发现不管是发心跳 还是做别的处理操作,都没有特别详细的说明!!
希望作者可以在努力优化一下!!!

另外还出现一个问题
 E/Socket: Socket服务器连接成功 211.154.132.85:7709
 E/libGLESv2: HWUI Protection: wrong call f
 E/Socket: write bytes: 60 00 00 00 1e 2b 4
 E/Socket: bytes write length:96
 E/RDS: onSocketWriteResponse 96
 E/Socket: read head: 53 00 00 00 
 E/Socket: need read body length: 83

读取包的时候 已经发现 正确的 body 有83个字节了.  
 这个时候 就一直停在这里等..    大约1分钟 后  出现以下问题

 E/Socket: read total length:83
 E/Socket: read head: 1c 27 ff ff 
 E/Socket: need read body length: -55524
 E/Socket: duplex read error,thread is dead with exception:com.xuhao.android.libsocket.impl.exceptions.ReadException: this socket input stream has some problem,wrong body length -55524,we'll disconnect
 E/Socket: duplex_read_thread is shutting down
 E/RDS: onSocketReadResponse
 E/RDS: data ==长度 ==== 83
 E/RDS: data == 协议号 15003

不知道 是什么情况造成的,,,希望作者大大 能解答一下! 这只是连接 socket 做一个登陆操作而已,都走不下去了,,  后续的接口更无法进行下去了.... 感觉很尴尬!

**Comment by DavidMGT** [comment]
你解决了么，我也遇到了，苦恼

**Comment by zhouke23** [comment]
我解决了，请看我另一个发言，接上面发文

**Comment by zhouke23** [comment]
另外你需要把发送和接受改成低字节来处理

**Comment by zhouke23** [comment]
@DavidMGT 另外你需要把发送和接受改成低字节来处理,另外你看一下我后面的发文<<接上面发文>>

**Comment by xuuhaoo** [comment]
@DavidMGT DA您需要看下您的服务器是Java还是C,如果是Java默认是大端字节序,如果是C默认是小端字节序,需要和服务端同学确认下
