### ISSUE TITLE
Socket Service 经常读取错误，导致client 离线

### ISSUE THREAD

**Issue by sanluku** [xuuhaoo/OkSocket#202]
具体的Log如下：
W/System.err: OkSocket, duplex read error,thread is dead with exception:com.xuhao.didi.core.exceptions.ReadException: read head is wrong, this socket input stream is end of file read -1 ,that mean this socket is disconnected by server
I/System.out: OkSocket, server_client_read_thread is shutting down

就算head读取错误，能否不断开client呢？

**Comment by Sohnia** [comment]
我刚刚试了一下也是总是断开client。

**Comment by sanluku** [comment]
> 我刚刚试了一下也是总是断开client。

操作问题，Client需要Service应答，否则Client会超时断开连接

**Comment by Sohnia** [comment]
> Reference

怎么实现呢，能否引用下代码，感激不尽

**Comment by Sohnia** [comment]
是不是需要服务端发心跳？

**Comment by sanluku** [comment]
> 是不是需要服务端发心跳？

服务端要回复客户端的心跳包
