### ISSUE TITLE
作者你好,接上面发文

### ISSUE THREAD

**Issue by zhouke23** [xuuhaoo/OkSocket#21]
刚修改了一下 你的接收的源码. 在得到了 body 长度的时候  减去包头 4字节的长度后
就可以正常运行,,

**Comment by xuuhaoo** [comment]
您的意思是我的Demo出现了问题么?您在哪个分支进行编译的,具体情况您可以加我qq说明,之后问题解决后您可以将解决思路贴出来,谢谢 183459684

**Comment by zhouke23** [comment]
你好作者,我是直接下载 zip文件的. 另外,您的demo 并没啥问题,只是说可能不适用于我工程,
原因如下:
完整包 86个字节  包含头 4个字节  body 82个字节 我这边项目的结构定义
1:而我在您demo 
 Reader.class 里面 
 ByteBuffer byteBuffer = ByteBuffer.allocate(bodyLength);
 这里减去了4个字节的包头长度 , 才可以正常使用!

因为作者 后续的处理是 
readBodyFromChannel() 这个方法,里面  while (byteBuffer.hasRemaining())  
是否有剩余字节的判断, 会一直阻塞 等待接收!  然后超时!

(我刚接触Socket  所以对其他的 定义结构规则不太了解,我只知道我们项目的这种处理方式)!

2:心跳问题,我项目这边,需要在未接收到心跳2次的时候 做一些处理,不知道作者这边的demo 是否有提供的回调?


谢谢作者大大!

**Comment by xuuhaoo** [comment]
另外,就您说的未接收到心跳2次需要做处理,目前是没有现成回调的,您可以通过重写PulseManager来进行满足您的业务需求,以后会开放关于自定义PulseManager的相关设置

**Comment by zhouke23** [comment]
作者:
       在没用OKSocket之前 都是自己手动写好了的,只是再无意间看到作者大大的作品,想尝试把原写好的底层改成使用OkSocket!
    我使用是的默认的配置! 然后得到的bodyLength 是完整包的包大小,并不是包体的大小, 所以我也很奇怪,但是如果我做了 bodyLength -4 以后 就能得到正确的 包体大小! 
    不知道是不是跟发包的结构有关系, 我这边发包结构 包头和包体 统一在一个 byte[] 里面, 然后发送出去!
    另希望作者大大可以多多加油优化!

**Comment by xuuhaoo** [comment]
你使用的是什么依赖,请使用jcenter的依赖,或者下载release分支的代码,master上是正在开发还没有完工的代码

**Comment by zhouke23** [comment]
我是把okStock作为library 然后在最外层的build.gradle 里面增加
classpath 'com.github.dcendents:android-maven-gradle-plugin:2.0'

可能正因为如此,可以修改成自己想要的,同时在你写好的代码上再进行 发包,收包的封装 来统一管理吧!

**Comment by xuuhaoo** [comment]
恩,注意你一来的library中的分支,master分支是还未开发完成的分支,请不要使用,请使用现在的release分支进行二次开发

**Comment by zhouke23** [comment]
我直接下的 zip包  应该是 release的吧? 我看demo 的名称叫
OkSocket-release-1.0.1!
期待作者大大 下版的优化!如果有更新,麻烦告知一下!!多谢!!!
