### ISSUE TITLE
数据问题.

### ISSUE THREAD

**Issue by lsqzero** [xuuhaoo/OkSocket#25]
您好,我现在的使用场景是连接一台wifi相机,通过Socket连接后,点击app中的拍摄,相机会发送一段数据到我的app,发送一个16位数3个字节.然后继续发一个1024*1280的照片数据. 
按照您readme中提示,我自定义了包头长度3,包体1024*1280,每次拍摄后的包头数据都不一致,所以现在我有点不清楚该怎么做.

**Comment by xuuhaoo** [comment]
我的理解是10241280这个数据代表着包体长度,您应该通过3个字节的包头解析获得10241280这个数字,而不是应该写死这个数据

**Comment by lsqzero** [comment]
很抱歉 这两天因为个人原因没有查看您的回复, 他是通过Socket发送给我1024x1280长度的数据,也就是一帧照片的数据, 但是他给我发送数据的时候是发送了两条数据,一条3个字节的,另一条为1024x1280.其中三个字节的数据是我发给服务器获取照片的指令,他捕获到返回给我,并且再发送一条1024x1280的数据.我做数据接收的时候,是直接写3个字节的包头,1024x1280的包体么,我不太了解Socket的通信机制
