### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by a7891749** [xuuhaoo/OkSocket#26]
12-22 17:47:44.725 13929-13941/com.dsh.client I/art: Background sticky concurrent mark sweep GC freed 772255(31MB) AllocSpace objects, 1(68KB) LOS objects, 0% free, 27MB/27MB, paused 943us total 117.273ms
12-22 17:47:45.190 13929-13941/com.dsh.client I/art: Background partial concurrent mark sweep GC freed 1036731(40MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 29MB/33MB, paused 942us total 157.429ms
12-22 17:47:45.718 13929-13941/com.dsh.client I/art: Background sticky concurrent mark sweep GC freed 1244577(48MB) AllocSpace objects, 0(0B) LOS objects, 7% free, 30MB/33MB, paused 1.189ms total 189.730ms
12-22 17:47:46.230 13929-13941/com.dsh.client I/art: Background sticky concurrent mark sweep GC freed 1238303(48MB) AllocSpace objects, 0(0B) LOS objects, 8% free, 30MB/33MB, paused 1.016ms total 188.813ms
12-22 17:47:46.707 13929-13941/com.dsh.client I/art: Background sticky concurrent mark sweep GC freed 1184767(46MB) AllocSpace objects, 0(0B) LOS objects, 9% free, 30MB/33MB, paused 966us total 152.452ms
12-22 17:47:47.187 13929-13941/com.dsh.client I/art: Background sticky concurrent mark sweep GC freed 1184742(46MB) AllocSpace objects, 0(0B) LOS objects, 9% free, 30MB/33MB, paused 903us total 154.748ms
12-22 17:47:47.701 13929-13941/com.dsh.client I/art: Background sticky concurrent mark sweep GC freed 1189576(46MB) AllocSpace objects, 0(0B) LOS objects, 8% free, 30MB/33MB, paused 963us total 173.634ms
viewpager 数据请求导致OOM 这个怎么解决 大佬

**Comment by xuuhaoo** [comment]
Socket通讯不会导致OOM,您看下您的场景,根据您的日志,我没有看出来是什么原因.您可以加我qq详细说明183459684

**Comment by xuuhaoo** [comment]
其实并没有oom,只是你的内存监控打印了日志而已.oom会有error抛出.请关闭refChecker

**Comment by a7891749** [comment]
嗯嗯
