### ISSUE TITLE
非常抱歉 这两天没有看您的回复.

### ISSUE THREAD

**Issue by lsqzero** [xuuhaoo/OkSocket#27]
很抱歉 这两天因为个人原因没有查看您的回复, 他是通过Socket发送给我1024x1280长度的数据,也就是一帧照片的数据, 但是他给我发送数据的时候是发送了两条数据,一条3个字节的,另一条为1024x1280.其中三个字节的数据是我发给服务器获取照片的指令,他捕获到返回给我,并且再发送一条1024x1280的数据.我做数据接收的时候,是直接写3个字节的包头,1024x1280的包体么,我不太了解Socket的通信机制

**Comment by xuuhaoo** [comment]
您可以加我 qq,183459684 之后我们一起解决,之后将解决方案贴到这里.

**Comment by lsqzero** [comment]
好的 已经加您了.

**Comment by lsqzero** [comment]
修改通讯协议,在包头中包含包体数据的长度.
因与Socket服务器为C代码.所以需要确认好字节序是大端还是小端.
修改后的设置代码如下:
`  mInfo = new ConnectionInfo(BaseConfig.IP, BaseConfig.PORT);
        mManager = OkSocket.open(mInfo);
        mOptions = mManager.getOption();
        mBuilder = new OkSocketOptions.Builder(mOptions);
        mBuilder.setConnectTimeoutSecond(BaseConfig.TIMEOUT);
        mBuilder.setReadByteOrder(ByteOrder.BIG_ENDIAN);
        mBuilder.setReadSingleTimeBufferBytes(BaseConfig.READBYTES);
        mBuilder.setHeaderProtocol(new IHeaderProtocol() {


            @Override
            public int getHeaderLength() {
                return 7;
            }

            @Override
            public int getBodyLength(byte[] header, ByteOrder byteOrder) {
                ByteBuffer headerBd = ByteBuffer.wrap(header);
                headerBd.order(byteOrder);
                int bodyLength = headerBd.getInt(3);
                return bodyLength;
            }
        });
        mManager.option(mBuilder.build());
        mManager.connect();
        mManager.registerReceiver(this);
`
