### ISSUE TITLE
we can't read data bigger than

### ISSUE THREAD

**Issue by Sabirjan** [xuuhaoo/OkSocket#3]
com.xuhao.android.libsocket.impl.exceptions.ReadException: we can't read data bigger than 10Mb
这个是什么错误啊？我的数据不超过3KB

**Comment by xuuhaoo** [comment]
![image](https://user-images.githubusercontent.com/10423664/31625232-ed8b5d3c-b26a-11e7-8450-de1c6a966dcf.png)
你的Socket服务器应该返回数据格式按照 [包头][包体]的格式,包头中默认的Header处理是直接解析包头数据为后面的包体长度,你可以重写包头解析方法,来适应你的服务器返回,从中返回正确的包体长度,如上图这个方法,是设置自定义包头解析类的

**Comment by xuuhaoo** [comment]
我已经更新了文档,你可以看下

**Comment by Sabirjan** [comment]
每一个包是 \n 来分包的，这个怎么解析？

**Comment by Sabirjan** [comment]
还有一个问题：我重写了那个接口，但是不知道当前的接受的数据，怎么知道一个包Body长度呢？

**Comment by Sabirjan** [comment]
有时间帮我解决一下，谢谢：QQ 253933559

**Comment by baizekeji** [comment]
我也是遇到这个问题，   怎么自定义包头和包体 ？

**Comment by Sabirjan** [comment]
目前为止好像不支持自定义分包

**Comment by baizekeji** [comment]
QQ  58461882  ， 求大佬支援

**Comment by baizekeji** [comment]
或者说这个   服务器 发送的 格式是什么

**Comment by xuuhaoo** [comment]
例如服务端要给你发送一个英文字母 a
那么服务端应该这样发送 byte 数组
00 00 00 01 61

解释如下:
a 的 Ascll 码对应的是97 97的16进制是0x61
a 的数据长度是1
所以包头要标识后面的包体长度是1
所以包头就是1
因为包头是 int 型,一个 int 型战4个字节
所以,就是00 00 00 01
要发送的数据长度 + 发送的数据
所以就是 00 00 00 01 61
