### ISSUE TITLE
我们自定义协议设置了头和尾，但是用了你的代码返回了超过10m了

### ISSUE THREAD

**Issue by qieyifei** [xuuhaoo/OkSocket#31]
int bodyLength = headerProtocol.getBodyLength(originalData.getHeadBytes(), mOkOptions.getReadByteOrder());    直接提示超过10m    我们的头是[top] 尾[end]
我用你的
       okOptionsBuilder.setHeaderProtocol(new IHeaderProtocol() {
            @Override
            public int getHeaderLength() {
                //Returns a custom header length that automatically parses the length of the head
                return "[top]".getBytes().length;
            }

            @Override
            public int getBodyLength(byte[] header, ByteOrder byteOrder) {
                //The length of the body is parsed from the header, byteOrder is the sequence of bytes that you configured in the parameter, which can be easily parsed using ByteBuffer
                if (header == null || header.length == 0) {
                    return 0;
                }
                if (ByteOrder.BIG_ENDIAN.toString().equals(byteOrder.toString())) {
                    return BytesUtils.bytesToInt2(header, 0);
                } else {
                    return BytesUtils.bytesToInt(header, 0);
                }
            }
        });

直接报异常了  我应该怎么设置啊   提示返回超过10m 也就几个字节 怎么可能超过10m

**Comment by w171066813** [comment]
现在你那个问题解决了吗，我也不知道怎么操作 能指导一下吗

**Comment by xuuhaoo** [comment]
@w171066813 你加我qq吧..
