### ISSUE TITLE
作者你好,请问怎么开启多个socket连接?

### ISSUE THREAD

**Issue by zhouke23** [xuuhaoo/OkSocket#32]
作者你好,想请问,我用您的oksocket 怎么同时开启2个或多个 socket连接,

**Comment by xuuhaoo** [comment]
OkSocket.open不同的ConnectionInfo就可以了

**Comment by zhouke23** [comment]
作者的意思是，我自己写两个管理类， 然后在在不同的管理类里面 new connectionInfo 是吧？
好的，我明天去试一下，，多谢，，
顺便问一句，作者，oksocket 支持DNS域名的连接模式吗？

**Comment by xuuhaoo** [comment]
不支持DNS域名的连接模式,另外不用谢两个管理类...直接用OkSocket.open(不同的Info)就可以得到两个Manager了.框架会管理这两个连接,负责断线重连,心跳等
