### ISSUE TITLE
大神，你好

### ISSUE THREAD

**Issue by Ambiton** [xuuhaoo/OkSocket#33]
你写的oksockect还是挺好用的，但是有时候会手机锁屏后会碰到onSocketWriteResponse方法一直不停调用的情况出现，我自己没有去发送Socket，而且心跳也没那么频繁，最后的结果是手机ANR 了，请问你又碰到这样的情况吗？

**Comment by xuuhaoo** [comment]
可能是框架之前的bug,已经处理,今晚升级到1.2.1尝试修复

**Comment by xuuhaoo** [comment]
版本已上传,如还有问题请更新,问题先关闭
