### ISSUE TITLE
与网络调试助手连接

### ISSUE THREAD

**Issue by w171066813** [xuuhaoo/OkSocket#35]
可以连接上  但是网络调试助手发一个 “1”过来都会报错：Caused by: com.xuhao.android.libsocket.impl.exceptions.ReadException: we can't read data bigger than 10Mb

**Comment by xuuhaoo** [comment]
认真阅读ReadMe说明,需要按照默认协议发送数据,发送1显然是不对的

**Comment by w171066813** [comment]
主页上的内容看了好几遍了不知道在哪改。。应该遵循什么数据协议？

**Comment by w171066813** [comment]
因为比较了一下 ，上次您更新的时候将

okOptionsBuilder.setHeaderProtocol(new IHeaderProtocol() {
    @Override
    public int getHeaderLength() {
    	//返回自定义的包头长度,框架会解析该长度的包头
        return 0;
    }

    @Override
    public int getBodyLength(byte[] header, ByteOrder byteOrder) {
    	//从header(包头数据)中解析出包体的长度,byteOrder是你在参配中配置的字节序,可以使用ByteBuffer比较方便解析
        return 0;
    }
});
这段给注销掉了 所以以为不需要设置什么直接可以接受到服务器的数据，但是现在我还是没搞明白服务器要给什么形式的数据，能稍微指点一下吗？感激不尽

**Comment by xuuhaoo** [comment]
加我qq吧
