### ISSUE TITLE
发送和接收 建议增加 无需包头 的情况。

### ISSUE THREAD

**Issue by loveanao** [xuuhaoo/OkSocket#37]
有些业务场景不需要包头..希望可以增加选项进行配置，感谢分享，目前只有下下来，改源码使用来了，总体很好用。。。

**Comment by xuuhaoo** [comment]
没有包头无法增加 因为不能处理拆包粘包

2018年1月23日 21:21，"loveanao" <notifications@github.com>写道：

**Comment by feaoes** [comment]
由于ObjectInputStream 以及ObjectOutputStream 序列化以及反序列化对象之后，不会出现拆包粘包的问题，所以建议加入 无需包头 的情况

**Comment by xuuhaoo** [comment]
以后可以提供自定义Reader和Header的

**Comment by shenzhigang** [comment]
@feaoes  效率问题，因为没有包长度信息，你是不知道当前stream里够不够反序列化出一个对象，够几个对象...每次尝试，显然效率太低。

**Comment by popmail** [comment]
我有个最简单的需求，我们的包是文本格式，以换行作为结束。貌似只能改代码
