### ISSUE TITLE
发送较大数据时，无法保持心跳？

### ISSUE THREAD

**Issue by Raralili** [xuuhaoo/OkSocket#42]
你好！首先非常感谢你的开源框架，对我帮助很大！现在我遇到了一些问题，就是我需要向服务端发送base64的图片数据，数据量较大，在心跳保持时间过后还没有传完数据，导致服务端关闭了socket连接。请问能有什么办法解决吗？

**Comment by xuuhaoo** [comment]
这么大的数据吗...如果数据一直传输,服务器不应该断开数据连接,是不是这种逻辑更正确些,心跳的作用是更新路由表,让运营商能够正确的将你的ip路由到指定的服务器,而不是中途dhcp进行切换,既然都在写数据了,就没有必要传输心跳了,因为心跳也是一种特殊的数据

**Comment by Raralili** [comment]
感谢！我也是这样想的。因为图片是手机拍的，数据长度接近7Mb，传输的过程中，过了心跳的间隔时间服务端就断开了。我看了下你的源码，因为我水平较低，虽然不大看得懂，我还是发现了，心跳的实现最终也是通过IConnectionManager发的，也就是同一个线程。本来我是说能不能用异步线程的方式在图片发送的期间也不影响心跳的发送，但是我想了一下这是根本不可能的，就算假设能实现异步，图片数据和心跳数据混在一起，那也是无法解析的。

**Comment by duanjisi** [comment]
发送图片的同时发送心跳包，其实也是可以的，只不过比较复杂，涉及到粘包的处理

**Comment by xuuhaoo** [comment]
对,但是没有必要
