### ISSUE TITLE
关于一个app连接2个服务端

### ISSUE THREAD

**Issue by makeloveandroid** [xuuhaoo/OkSocket#44]
1个app同时连接2个相同地址,不同端口的服务器,第二个连接的无法收到数据

**Comment by xuuhaoo** [comment]
请检查代码是否写错,如果不能解决问题,请加我qq 183459684

**Comment by makeloveandroid** [comment]
解决了,是你Reader read()方法里面加了同步代码块,锁用的是Reader.class,因为我是2个连接对象,用了一个锁里面的mInputStream.read() 方法又是中断的,所以导致另外一个收不到消息

**Comment by 382202771** [comment]
可以说下是怎么解决的么 我也遇到了这个问题。
