### ISSUE TITLE
manager.disconnect无效

### ISSUE THREAD

**Issue by wanyt** [xuuhaoo/OkSocket#45]
在onDestory里面调用disconnect，重新打开应用的时候，再次链接会多次触发onSocketConnectionSuccess，这个怎么解决

**Comment by xuuhaoo** [comment]
您加我qq吧183459684,有可能你的Activity对象没有销毁,导致注册了多个监听器对象,你的监听器对象估计是个匿名内部类

**Comment by santosunny** [comment]
在onDestroy生命周期里调用unregister方法，
    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (manager != null && manager.isConnect()) {
            manager.disConnect();
            manager.unRegisterReceiver(adapter);
            manager = null;
        }
    }
或者监听器只随manager的创建绑定一次
        manager = OkSocket.open(info);
        manager.registerReceiver(adapter);

**Comment by xuuhaoo** [comment]
完美解决,谢谢 @santosunny
