### ISSUE TITLE
数据传输  - 延迟

### ISSUE THREAD

**Issue by Lijinqi** [xuuhaoo/OkSocket#46]
大佬  传输数据时  频率快，然后每次传输数据较大的时候会有延时...我server用的是demo...这个有什么建议吗？

**Comment by xuuhaoo** [comment]
183459684加我说

**Comment by Lijinqi** [comment]
已经解决了问题。1、数据延迟是因为初始化  OkSocket.initialize(this,true); 开启了debug导致耗时。 关闭效果很好   2、然后会有断线重连的问题。是因为
//在主进程初始化一次,多进程时需要区分主进程.
OkSocket.initialize(this);
多进程没有区分主进程。  还有我不得不说大佬很强  恩 很感谢大佬花时间帮我看bug!!!
