### ISSUE TITLE
关于多个socket在后台的存活时间问题

### ISSUE THREAD

**Issue by kbxwn** [xuuhaoo/OkSocket#47]
你好，请问下使用OkSocket.open()得到多个connectionManager，对每个connectionManager设置不同的OkSocketOptions.mBackgroundLiveMinute，即在后台的存活时间，查看了下EnvironmentalManager类的mHandler的处理，发现是对所有的connectionManager进行disConnect的处理，即使每个connectionManager的mBackgroundLiveMinute不同，请问下这样处理的原因是什么呢？

**Comment by xuuhaoo** [comment]
后台存活时间设计的是不针对每个链接,而是针对全部链接,原因是这个设计为了后台省电,如果仅断开一个链接不能达到省电的目的.请您使用1.2.3版本,该版本对后台存活时间进行了bug修复,之前设置会有问题

**Comment by kbxwn** [comment]
了解
