### ISSUE TITLE
您好，请问报这个错怎么解决呢。

### ISSUE THREAD

**Issue by cwzevoli** [xuuhaoo/OkSocket#53]
com.xuhao.android.libsocket.impl.exceptions.ReadException: com.xuhao.android.libsocket.impl.exceptions.ReadException: we can't read data bigger than 10Mb
03-22 16:59:59.000 2832-2929/com.blx.blxevdetector W/System.err:     at com.xuhao.android.libsocket.impl.blockio.io.ReaderImpl.read(ReaderImpl.java:111)
03-22 16:59:59.000 2832-2929/com.blx.blxevdetector W/System.err:     at com.xuhao.android.libsocket.impl.blockio.threads.DuplexReadThread.runInLoopThread(DuplexReadThread.java:35)
03-22 16:59:59.000 2832-2929/com.blx.blxevdetector W/System.err:     at com.xuhao.android.libsocket.impl.LoopThread.run(LoopThread.java:50)
03-22 16:59:59.000 2832-2929/com.blx.blxevdetector W/System.err:     at java.lang.Thread.run(Thread.java:818)
03-22 16:59:59.000 2832-2929/com.blx.blxevdetector W/System.err: Caused by: com.xuhao.android.libsocket.impl.exceptions.ReadException: we can't read data bigger than 10Mb
03-22 16:59:59.000 2832-2929/com.blx.blxevdetector W/System.err:     at com.xuhao.android.libsocket.impl.blockio.io.ReaderImpl.read(ReaderImpl.java:63)
03-22 16:59:59.000 2832-2929/com.blx.blxevdetector W/System.err: 	... 3 more

**Comment by xuuhaoo** [comment]
按照协议来,服务器给你的协议不对,具体的看下readme
