### ISSUE TITLE
disConnect后并没有真正的断开

### ISSUE THREAD

**Issue by DizzyYang** [xuuhaoo/OkSocket#56]
作者你好

先说流程

Socket -> 连接 -> onSocketConnectionSuccess

执行验证

                if (mManager != null) {
                    mManager.send(new SocketAuthData());
                }

验证成功回调

然后执行退出界面

                @Override
                 protected void onDestroy() {
                        super.onDestroy();
                        if(mManager != null){
                            mManager.disConnect();
                        }
                 }

程序进入后台

再次打开程序执行以上方法

执行验证

                if (mManager != null) {
                    mManager.send(new SocketAuthData());
                }

验证成功回调

这里好像又发送了一条空的数据

但不是我发送的，这里只执行一次验证

具体是什么问题还不清楚

应该是上次关闭程序Socket并没有Dis的问题

导致 bodyLength < 0 报错

                } else if (bodyLength < 0) {
                throw new ReadException(
                        "this socket input stream has some problem,wrong body length " + bodyLength
                                + ",we'll disconnect");
                }

-> onSocketDisconnection

具体问题还没有筛出来

修改 mManager = null

                @Override
                 protected void onDestroy() {
                        super.onDestroy();
                        if(mManager != null){
                            mManager.disConnect();
                            mManager = null;
                        }
                 }

问题暂时解决

**Comment by xuuhaoo** [comment]
首先,感谢你的问题描述如此清晰

其次,我建议你打开OkSocket日志功能进行排查,
this socket input stream has some problem,wrong body length
说明是服务器发过来的input流里面出现脏数据,那么需要看下是否是服务端有问题

如果问题还未能正确排查出,请加我qq,183459684,我会协助你解决问题,之后在此公布解决方案

**Comment by DizzyYang** [comment]
根据log我看了一下

当我打开连接管理保存

options.setConnectionHolden(true);
options.setReconnectionManager(new DefaultReconnectManager());

按照我提出的问题的流程进行

第二次连接出现

两条相同的write bytes

服务器只验证一次，第二次不予处理，所以会出现ff ff ff ff ff ff

具体Log

Socket: Socket服务器连接成功 192.168.0.109:8081
Socket: write bytes: 00 03 00 00 00 
Socket: bytes write length:11
Socket: write bytes: 00 03 00 00 00 
Socket: bytes write length:11
Socket: read head: 00 04 00 00 00 00 
Socket: need read body length: 0
Socket: read head: ff ff ff ff ff ff 
Socket: need read body length: -1
System.err: com.xuhao.android.libsocket.impl.exceptions.ReadException: com.xuhao.android.libsocket.impl.exceptions.ReadException: this socket input stream has some problem,wrong body length -1,we'll disconnect

**Comment by xuuhaoo** [comment]
看一下你是否没有解除注册监听器,因为监听器是全局的,如果注册了,需要注意销毁

**Comment by DizzyYang** [comment]
感谢作者的回复

确实如你所说并没有注销

已修改

                @Override
                 protected void onDestroy() {
                        super.onDestroy();
                        if(mManager != null){
                            mManager.disConnect();
                            mManager.unRegisterReceiver(socketActionAdapter);
                        }
                 }
