### ISSUE TITLE
手机锁屏之后，再打开，为什么会走一次连接过程

### ISSUE THREAD

**Issue by cwzevoli** [xuuhaoo/OkSocket#57]

**Comment by cwzevoli** [comment]
测试了一下是断开连接了，库中有方法在app销毁之前一直保持连接吗

**Comment by xuuhaoo** [comment]
因为为了省电,当App至于后台1分钟(默认值)会自动断开连接,当App至于前台,立马回进行恢复连接,如果不希望有这个功能,请参考OkOption中的后台存活时间,将其设置为-1
