### ISSUE TITLE
请问如何使用该框架传送较大的文件？

### ISSUE THREAD

**Issue by hyc1007** [xuuhaoo/OkSocket#60]
框架只提供了发送byte数组的方法，如果将大文件先全部转换为byte数组，则肯定会发生oom异常。是否考虑支持发送时从inputStream读取数据，接受时，将数据写入outputStream,来完成传输大文件的功能

**Comment by hyc1007** [comment]
想实现2个手机之间互传文件，客户端使用本框架的话 ，服务端是否还需要使用其他框架才可以搭建？这样分段将大文件转换为字节，加包头长度的方法，比较麻烦吧，相当于自己手动将文件分包。能否增加一个直接从inputSteam读取的方法，这样就可以直接一次性将大文件发送出去。服务端解析起来也比较方便

**Comment by xuuhaoo** [comment]
日后可以考虑
