### ISSUE TITLE
点击断开连接 执行 mManager.disConnect() 报异常了，帮忙看下原因

### ISSUE THREAD

**Issue by flyjiang2014** [xuuhaoo/OkSocket#62]
04-09 10:22:28.634 26748-26778/com.xuhao.android.oksocket E/Socket: duplex read error,thread is dead with exception:java.net.SocketException: socket is closed
04-09 10:22:28.634 26748-26748/com.xuhao.android.oksocket E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xuhao.android.oksocket, PID: 26748
    android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
        at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:300)
        at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1194)
        at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1189)
        at com.xuhao.android.libsocket.impl.BlockConnectionManager.disConnect(BlockConnectionManager.java:272)
        at com.xuhao.android.libsocket.impl.BlockConnectionManager.disConnect(BlockConnectionManager.java:297)

**Comment by flyjiang2014** [comment]
try {
                mSocket.close();
            } catch (IOException e) {
            }
            mSocket = null;

 mSocket.close();就是这句

**Comment by xuuhaoo** [comment]
关闭你的StrictMode

**Comment by xuuhaoo** [comment]
请问什么机型

**Comment by flyjiang2014** [comment]
小米6

**Comment by flyjiang2014** [comment]
应该跟机型没啥关系，我用其他手机，模拟器试了都会报错

**Comment by xuuhaoo** [comment]
实际测试了,没有发现问题,你重新checkout一下demo项目,直接run看下

**Comment by flyjiang2014** [comment]
demo没有问题，会不会跟我用的sslSocket有关系，你测试的时候有没有用 sslSocket
sslSocket断点信息：
mSocket = {OpenSSLSocketImpl@4943} "Socket[address=XXXXXXXXXXX,port=10087,localPort=56340]"
 autoClose = false
 channelIdPrivateKey = null
 guard = {CloseGuard@4962} 
 handshakeSession = null
 handshakeTimeoutMilliseconds = -1
 is = {OpenSSLSocketImpl$SSLInputStream@4963} 
 listeners = null
 os = {OpenSSLSocketImpl$SSLOutputStream@4964} 
 peerHostname = "XXXXXXXXXXX"
 peerPort = -1
 readTimeoutMilliseconds = 0
 socket = {OpenSSLSocketImpl@4943} "Socket[address=XXXXXXXXXXX,port=10087,localPort=56340]"
 sslNativePointer = 547195613952
 sslParameters = {SSLParametersImpl@4966} 
 sslSession = {OpenSSLSessionImpl@4967} 
 state = 4
 stateLock = {Object@4968} 
 writeTimeoutMilliseconds = 0
 bound = true
 closeLock = {Object@4969} 
 closed = false
 connected = true
 created = true
 impl = {SocksSocketImpl@4970} "Socket[addr=XXXXXXXXXXX,port=10087,localport=56340]"
 oldImpl = false
 shutIn = false
 shutOut = false
 shadow$_klass_ = {Class@2399} "class com.android.org.conscrypt.OpenSSLSocketImpl"
 shadow$_monitor_ = -1948952833

另外在 OnCreate方法中设置 StrictMode模式
    StrictMode.ThreadPolicy policy=new StrictMode.ThreadPolicy.Builder().permitAll().build();
      StrictMode.setThreadPolicy(policy); 可以规避这个异常。但是这个违背google设计原则，这个异常还是在主线程中做耗时的网络操作引起的

**Comment by xuuhaoo** [comment]
确实没有测试过ssl.我看下

**Comment by xuuhaoo** [comment]
您能帮我测试下,如果在Thread中使用disconnect会有问题么,不改StrictMode

**Comment by flyjiang2014** [comment]
是 Activity 类中调用  mManager.disConnect(); 放在 Thread中，还是 直接把BlockConnectionManager类调用
mSocket.close(); 放在 Thread中，两个操作分别试了下，都可以正常的关闭和连接。

**Comment by xuuhaoo** [comment]
请使用2.0.0-beta解决此问题
