### ISSUE TITLE
OkSocket接收服务器数据是一直提示无法读取大于10Mb的数据

### ISSUE THREAD

**Issue by JWJevon** [xuuhaoo/OkSocket#65]
com.xuhao.android.libsocket.impl.exceptions.ReadException: com.xuhao.android.libsocket.impl.exceptions.ReadException: we can't read data bigger than 10Mb
04-12 16:20:10.025 30471-5841/com.xuhao.android.oksocket W/System.err:     at com.xuhao.android.libsocket.impl.blockio.io.ReaderImpl.read(ReaderImpl.java:111)
04-12 16:20:10.026 30471-5841/com.xuhao.android.oksocket W/System.err:     at com.xuhao.android.libsocket.impl.blockio.threads.DuplexReadThread.runInLoopThread(DuplexReadThread.java:35)
04-12 16:20:10.026 30471-5841/com.xuhao.android.oksocket W/System.err:     at com.xuhao.android.libsocket.impl.LoopThread.run(LoopThread.java:50)
04-12 16:20:10.026 30471-5841/com.xuhao.android.oksocket W/System.err:     at java.lang.Thread.run(Thread.java:761)
04-12 16:20:10.027 30471-5841/com.xuhao.android.oksocket W/System.err: Caused by: com.xuhao.android.libsocket.impl.exceptions.ReadException: we can't read data bigger than 10Mb
04-12 16:20:10.027 30471-5841/com.xuhao.android.oksocket W/System.err:     at com.xuhao.android.libsocket.impl.blockio.io.ReaderImpl.read(ReaderImpl.java:63)
04-12 16:20:10.027 30471-5841/com.xuhao.android.oksocket W/System.err: 	... 3 more
04-12 16:20:10.027 30471-5841/com.xuhao.android.oksocket E/Socket: duplex read error,thread is dead with exception:com.xuhao.android.libsocket.impl.exceptions.ReadException: we can't read data bigger than 10Mb

**Comment by 353338110** [comment]
我也一直报这个问题。请问是什么原因？

**Comment by xuuhaoo** [comment]
已经优化了错误文案,请使用最新版本2.0.0-beta
