### ISSUE TITLE
重连问题

### ISSUE THREAD

**Issue by LiuYiAC** [xuuhaoo/OkSocket#66]
你好，我发现有这么一个问题，如果我在自动重连的时候，手动重连了，偶尔会发生自动重连成功，手动重连也成功，在mConnectionManager里面我也没有发现不让自动重连的方法，怎样才能保证在重连的时候始终只有一个客户端啊？

**Comment by JWJevon** [comment]
你好，我想问题一下你，怎么把接收和发送前面的4位int类型给去掉，我看见楼主说换成自己的，但是我不知道怎么弄，如果可以的话，麻烦告诉我一下，谢谢

**Comment by JWJevon** [comment]
楼主的我的看到懂，但是不知道怎么弄，至于第二个你说的，我之前就试多了不可以，除非你还修改了别的地方，如果方便的话，可以加QQ吗？2455524225

**Comment by LiuYiAC** [comment]
第二个为什么不行？接收到的数据有问题？

**Comment by JWJevon** [comment]
如果发送的十六进制时加00 00 00 长度的话 可以 这个就是最开始代码的效果，但是我不想要他，而你说的还是不可以    我无论是清除4还是清除bb.putInt(body.length);或者都清除还是不可以，项目我刚刚故意删除了，从新压缩还是不可以，如果可以的话，加我QQ可以吗？

**Comment by JWJevon** [comment]
最开始的是什么意思，就是项目刚刚下载的时候吗？不是需要在DefaultNormalHeaderProtocol 从新写吗？我是修改他网站上提示的修改解码的包头，你这里是什么设置的？但是我设置0就是不行，如果可以的话加我QQ，这样交流有些麻烦。

**Comment by LiuYiAC** [comment]
加你QQ了

**Comment by JWJevon** [comment]
我QQ是2455524229 姓名是揭文，上面的打错了   不好意思
