### ISSUE TITLE
麻烦各位兄弟,了解修改心跳时间的配置的,帮提一下建议

### ISSUE THREAD

**Issue by WZRRRRRR** [xuuhaoo/OkSocket#68]
//连接参数设置(IP,端口号)
    ConnectionInfo info = new ConnectionInfo("192.168.8.110", 6563);
    //调用OkSocket,开启这次连接的通道,拿到通道Manager
    IConnectionManager manager = OkSocket.open(info, mOkOptions);
    //获得当前连接通道的参配对象
    OkSocketOptions options = manager.getOption();
    //基于当前参配对象构建一个参配建造者类
    OkSocketOptions.Builder builder = new OkSocketOptions.Builder(options);
    //修改参配设置(其他参配请参阅类文档)
    builder.setPulseFrequency(3000);
    //建造一个新的参配对象并且付给通道
    manager.option(builder.build());
    //调用通道进行连接
    manager.connect();
现在的OkSocket.open需要两个参数 ,后面必须要一个OkOptions,这个参数我需要怎么初始化,或者怎么获取到,因为我现在mOkOptions是空,所以 OkSocketOptions.Builder builder = new OkSocketOptions.Builder(options); 这句话报空指针

**Comment by xuuhaoo** [comment]
这个open会在日后优化成一个,日后还会增加server端的代码
OkOptions.getDefault()可以帮你解决问题

**Comment by WZRRRRRR** [comment]
好的,谢谢
