### ISSUE TITLE
您好，send 指令的时候，在服务器收到的数据显示是分包形式的

### ISSUE THREAD

**Issue by cwzevoli** [xuuhaoo/OkSocket#69]
请问框架中的发送数据方法是直接发送一整条还是分包发送的？

**Comment by cwzevoli** [comment]
在服务器显示分包的情况，总是 第一个包是50字节

**Comment by xuuhaoo** [comment]
嗯,框架中有分包逻辑,默认是50字节

**Comment by xuuhaoo** [comment]
这个可以根据OkOption进行配置,看下OkOption的文档注释,不懂得提回复我来解答

**Comment by 1369900847** [comment]
怎么修改分包逻辑？

**Comment by xuuhaoo** [comment]
![image](https://user-images.githubusercontent.com/10423664/38988615-6f077fc6-4406-11e8-98bd-d6d7b5b6c163.png)
