### ISSUE TITLE
Some permissions required is unnecessary and useless in this library

### ISSUE THREAD

**Issue by fython** [xuuhaoo/OkSocket#7]
There are three permissions I questioned:

```xml
<uses-permission android:name="android.permission.GET_ACCOUNTS"/>
<uses-permission android:name="android.permission.READ_PROFILE"/>
<uses-permission android:name="android.permission.READ_CONTACTS"/>
```

As a socket library, it needn't get user accounts, read profile or contacts. In this library, these permissions are required but useless.

Maybe you can remove them from `README.md` and `README-CN.md` .

**Comment by xuuhaoo** [comment]
ops! really sorry .It will be removed as soon as possible tks
