### ISSUE TITLE
WebSocket支持？

### ISSUE THREAD

**Issue by JeremyLam1** [xuuhaoo/OkSocket#70]
服务端用的是WebSocket？oksocket没有访问url的方式，请问支持吗？

**Comment by xuuhaoo** [comment]
不支持

**Comment by JeremyLam1** [comment]
感谢作者回复，请问支持ssl这块完善了吗？看其他issue好像说有问题

**Comment by xuuhaoo** [comment]
ssl这块是因为需要在线程中关闭,目前没有文档说明,所以将在下一个版本完善,目前如果使用,请在断开的时候在线程中执行disconnect即可
