### ISSUE TITLE
关于向服务端发送数据报错问题

### ISSUE THREAD

**Issue by mynameisxw** [xuuhaoo/OkSocket#76]
当我使用mManager.send发送数据到服务端时，如果字符串稍微大点时报错_this socket input stream has some problem,wrong body length -15,we'll disconnect_，当传的字符串较小时正常，请问怎么解决

**Comment by xuuhaoo** [comment]
请您关注Demo中的调用,另外服务器返回的数据可能不正确,导致包头解析出来的包体数据不正确.您可以打开OkSocket的日志功能,找到对应的返回数据.
这里解析到body length是-15长度,所以说不正确.
您可以关注下是否是分包导致的,如果是分包导致的,是否让服务器调整下分包

**Comment by KeaPin** [comment]
这位问题除了服务端调整，有什么解决办法吗，因为服务端已经是第三方的，基本上不可能改的

**Comment by KeaPin** [comment]
@xuuhaoo 可以留一下联系方式吗，项目被卡主了，就差这个了

**Comment by BlueSky15171** [comment]
我在application里调用了OkSocket.initialize(this);
activity里上下文为空咋回事?

**Comment by xuuhaoo** [comment]
@BlueSky15171  您是不是多进程程序,注意下文档中强调了,需要区分主进程和其他进程
