### ISSUE TITLE
ReadException  recvfrom failed  断线重连

### ISSUE THREAD

**Issue by 382202771** [xuuhaoo/OkSocket#77]
W/System.err: com.xuhao.android.libsocket.impl.exceptions.ReadException: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
 W/System.err: at com.xuhao.android.libsocket.impl.blockio.io.ReaderImpl.read(ReaderImpl.java:111)
W/System.err:     at com.xuhao.android.libsocket.impl.blockio.threads.DuplexReadThread.runInLoopThread(DuplexReadThread.java:35)
W/System.err:     at com.xuhao.android.libsocket.impl.LoopThread.run(LoopThread.java:50)
W/System.err:     at java.lang.Thread.run(Thread.java:818)

您好 这个看的是读取数据的错误 可是我实际是在发送数据时出现的这个问题 麻烦指点下？

**Comment by 382202771** [comment]
发送数据时候会持续断线重连。

**Comment by 382202771** [comment]
//在主进程初始化一次,多进程时需要区分主进程. 
这句该怎么理解？可以说详细点么，谢谢。

**Comment by xuuhaoo** [comment]
多进程的应用,程序的Application的OnCreate会执行多次,需要进行区分,哪一次是在主进程

**Comment by xuuhaoo** [comment]
https://blog.csdn.net/smilingleo/article/details/133904

关于Connection reset by peer

**Comment by 382202771** [comment]
谢谢 问题已解决

**Comment by xuuhaoo** [comment]
能否在此说下解决问题的方式,或者问题发生在哪里,怎么解决的.帮助更多的人

**Comment by 382202771** [comment]
服务端用的是superSocket  我给他发送的数据也是4个字节的包头加包体，实际4个字节的包头长度是包体的长度，但是服务端理解的4个字节的长度为包头加包体的长度，解析时候出现了不对应，就出现了我上面的那个问题。其实就是相互之间的协议没有一致，再次谢谢作者提供了这么优秀的框架。谢谢！
