### ISSUE TITLE
有没有设置数据优先级的功能？

### ISSUE THREAD

**Issue by 382202771** [xuuhaoo/OkSocket#78]
您好，我现在有个问题是这样的，有一包服务器发过来的报警数据需要接收到立刻处理，可是之前收到的音频数据还没处理完，报警数据会在音频数据处理完之后才能处理，有没有办法设置个优先级什么的让我立刻能处理到比较重要的那包数据？或者有没有什么思路提供下，谢谢！

**Comment by xuuhaoo** [comment]
思路就是,你和服务器约定,单独建立一个socket进行这个报警数据处理.而不是和你业务socket一起.因为套接字是流式的,所以单个套接字没法完成你要的需求,建议你两个socket

**Comment by 382202771** [comment]
好的 谢谢！
