### ISSUE TITLE
重读读取header

### ISSUE THREAD

**Issue by 353338110** [xuuhaoo/OkSocket#79]
你好。我这边设置header大小大为4，然后就会一直读取body的下一个大小为4的byte。
比如我获取的是{1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5}
然后返回header{1,1,1,1} 
然后又返回{2,2,2,2}
{3,3,3,3}
{4,4,4,4}
请问这个是哪里没配置对吗？

**Comment by 353338110** [comment]
感谢回答。我现在用的是2.0.0-beta版本，使用方法同demo里面的SimpleDemoActivity，但是还是有出现这个问题。

**Comment by xuuhaoo** [comment]
您自定义了header了吗

**Comment by xuuhaoo** [comment]
我没有太理解你的问题是什么.描述的不是很清楚.您期望是怎样的,现在又是怎样的,您做了什么设置,麻烦写清楚下,我来跟进.

**Comment by 353338110** [comment]
是的。自定义的。
.setHeaderProtocol(new IHeaderProtocol() {
                    @Override
                    public int getHeaderLength() {
                        return 4;
                    }

                    @Override
                    public int getBodyLength(byte[] header, ByteOrder byteOrder) {
                        if (header == null || header.length == 0) {
                            return 0;
                        }
                        String heard = bytesToHexString(header);

                        if (heard.length()>=8 || heard.substring(0,4).toLowerCase().equals(_CMDProtocolHex)){
                            String strLong = heard.substring(6,7)+heard.substring(7,8)+heard.substring(4,5)+heard.substring(5,6);
                            
                         int i = Integer.parseInt(strLong,16);
                        }else {
                            return 0;
                        }
                    }
                })

这是我自定义的HeaderProtocol，但是每次运行的时候
