### ISSUE TITLE
解析服务器返回的数据的一点疑问

### ISSUE THREAD

**Issue by dakun666** [xuuhaoo/OkSocket#8]
您好大神，很清新的一个socket框架！火钳刘明！
我在看README的时候看到解析服务器返回的数据是set一个自定义的IHeaderProtocol，在getHeaderLength中返回包头的长度。在getBodyLength返回数据的长度，但是getBodyLength的方法参数只是(byte[] header, ByteOrder byteOrder),我没明白如何通过这两个参数获取到包体的长度。是需要我在其他地方获取或者保存整个消息体的长度？还是说服务器在包头中给我把包体的长度包含进去？亦或是其他方法？

**Comment by dakun666** [comment]
抱歉，我应该在头部去取包体的长度。已经解决了，再次感谢您的库

**Comment by xuuhaoo** [comment]
是的.应该与服务器协商通讯协议时,在包头里返回内中中加上包体长度的定义,当然包头不一定只有包体长度这一个数据,包头可以包含很多数据,例如功能号, CRC 校验码,包体长度,时间戳等等.根据业务需求和场景自行定义,框架主要负责通讯,处理 socket 的粘拆包,通讯断线重连,心跳等机制.如有问题欢迎 issues
