### ISSUE TITLE
Output and input

### ISSUE THREAD

**Issue by Alireza-Razavi** [xuuhaoo/OkSocket#80]
Is this just for one way connection? 
Client mobile just can send data and server mobile just can receive ????

**Comment by xuuhaoo** [comment]
No is duplex connection.
OkSocket is a Android socket client has send data and receive data ability.
What it your question?How can I help you.

**Comment by xuuhaoo** [comment]
![image](https://user-images.githubusercontent.com/10423664/39504162-4ee4113c-4dfc-11e8-8452-b831cae3d422.png)

**Comment by davyhi** [comment]
why the OkSocket client receives server data must be in a certain format? Can I modify it to suit my own need? will you please give me some suggestions so that this framework can be more applicable.
