### ISSUE TITLE
CPU占用率到60左右了

### ISSUE THREAD

**Issue by hai0shen** [xuuhaoo/OkSocket#81]
用来接收H264帧数据，是否因为帧数据太长，太大了导致的？

**Comment by hai0shen** [comment]
还想问下有没有直接获取Socket的IntputStream的getter方法来自己读取数据

**Comment by xuuhaoo** [comment]
如果你需要直接获得inputstream,您直接自己写socket就可以了,请通过安卓的性能分析来确定是那个函数占用了cpu
