### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [xuuhaoo/OkSocket#83]
If the project needs logo, I am willing to give my best design for this. Thanks PO !

**Comment by loydjayme25** [comment]
How about this sir ?
I am open for any suggestions

![proposal](https://user-images.githubusercontent.com/37318022/39992794-7915a3ae-57a6-11e8-9385-1241fd291644.png)

**Comment by loydjayme25** [comment]
The concept of the design : 
- Shield is the main common equipment in blocking
- The helmet will serve as the guard of the app

**Comment by xuuhaoo** [comment]
Can you show the Android logo, such as a robot, because the design of OkSocket is a Socket communication framework used by Android developers.

**Comment by loydjayme25** [comment]
i will add it sir,

**Comment by xuuhaoo** [comment]
Thank you very much.I am very glad to receive your Logo support.
