### ISSUE TITLE
怎么设置不指定长度接收消息？

### ISSUE THREAD

**Issue by ZhengJiao** [xuuhaoo/OkSocket#85]
制定长度接收没有任何问题，不指定长度接收不到？
希望可以建一个QQ群；这样方便讨论遇到的问题；

**Comment by ZhengJiao** [comment]
OkSocket作者非常好，不仅技术好，解决问题非常耐心；一个大大的赞送给作者；非常感谢；

**Comment by xuuhaoo** [comment]
客气了.
