### ISSUE TITLE
this socket input stream is end of file read -1 ,we'll disconnect

### ISSUE THREAD

**Issue by xesun** [xuuhaoo/OkSocket#87]
mManager.send { loginMessage.toString().toByteArray() }  after this error How to solution

**Comment by xuuhaoo** [comment]
This error is most likely due to your server shutting down the output stream.

**Comment by xesun** [comment]
But setheaderoption defualt length set after readdata receive response how to dynamic header body length please

**Comment by xuuhaoo** [comment]
I don't understand what's you mean.
We offer you method set the Header protocol to dynamic changing the body length as follow:
![image](https://user-images.githubusercontent.com/10423664/40111859-b53bcafc-5936-11e8-9c05-e14532cc1d56.png)

**Comment by guestOfGithub** [comment]
我也遇到了同样的问题，问下服务器那边说是客户端这边主动断开了，请问怎么处理下

**Comment by lilingdan** [comment]
do you have any method to receive buffer from server like   0xaa 0x11 0x02 0x42 0x43 0xff ,the buffer doesn't have header which repersents the length of buffer but just 0xaa 0x11? i need completed buffer,then parse by myself

**Comment by xuuhaoo** [comment]
If you want parse by yourself you can use original socket directly .
