### ISSUE TITLE
执行activity.recreate导致闪退

### ISSUE THREAD

**Issue by JeremyLam1** [xuuhaoo/OkSocket#88]
**执行activity.recreate导致闪退，注释掉OkSocket.initialize(this, BuildConfig.isDebug);则可以recreate。请lz看下谢谢，比较急。**
还有我根据自己业务使用registerActivityLifecycleCallbacks对activity管理，发现OkSocket.initialize(this, BuildConfig.isDebug);也是用了registerActivityLifecycleCallbacks，两者一起是否会有冲突？

**Comment by xuuhaoo** [comment]
由于最新引入的ActivityStack存在非致命缺陷,已经定位到并且修复,一起修复的还有ActivityStack的其他问题.请引用最新的版本2.0.1
