### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [xuuhaoo/OkSocket#89]
Hi, @xuuhaoo I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by xuuhaoo** [comment]
Opinions are open and we are welcome the new logo for this lib.

**Comment by mansya** [comment]
I have design a logo for this app. do you like it ? what do you think ?
![oksocket](https://user-images.githubusercontent.com/33461607/41199812-e52ed3ae-6cc2-11e8-976c-e15a60b22342.png)

**Comment by xuuhaoo** [comment]
It looks like great!!!

but I think it not green is better~

tks bro

**Comment by mansya** [comment]
would you give me the RGB color code you like?

**Comment by mansya** [comment]
would you give me the RGB color code you like?

**Comment by xuuhaoo** [comment]
I don't know witch color is better..

**Comment by mansya** [comment]
I have created a color variation. which one do you like ?
![variation](https://user-images.githubusercontent.com/33461607/41268947-c6dde85c-6e2c-11e8-98e8-38c1ad13b8ca.png)

**Comment by xuuhaoo** [comment]
I prefer the sixth what do you think?

**Comment by mansya** [comment]
yes. it looked good. I've uploaded all files in this link.
https://drive.google.com/open?id=15dwYSdtr5sj0q5UBqc6jvZb9cVCCmLRg

and I have also sent you pull requests. please check

**Comment by mansya** [comment]
Hi xuuhaoo, I have replace all new logo with the android logo. please check. maybe this will make you lighter and don't have to replace it yourself
