### ISSUE TITLE
如何更换ip

### ISSUE THREAD

**Issue by fail572872916** [xuuhaoo/OkSocket#9]
有没有更换Ip的功能

**Comment by xuuhaoo** [comment]
请具体描述下,更换IP的意思,是类似负载均衡吗,可以更换IP.Demo里面有相关的例子,一个重定向

**Comment by fail572872916** [comment]
例如从192.168.0.xxx到xxx

**Comment by xuuhaoo** [comment]
你可以参照例子中的MainActivity
您的需求是备用线路还是服务器负载均衡 需要您连接新的地址？

**Comment by xuuhaoo** [comment]
![image](https://user-images.githubusercontent.com/10423664/32480437-d52de1f4-c3c9-11e7-8700-0e84c3d65f52.png)

![image](https://user-images.githubusercontent.com/10423664/32480545-4b352be6-c3ca-11e7-9ad9-3346dc7ab602.png)

**Comment by xuuhaoo** [comment]
如果解决问题,我关闭了
