### ISSUE TITLE
若服务端传回的数据不携带表示长度的包头信息这个库就无法使用？

### ISSUE THREAD

**Issue by lilingdan** [xuuhaoo/OkSocket#91]
另外服务器传回的数据中含有0xff ,直接会抛出异常断开重连，我想知道哪些字符是被禁止的？

**Comment by ppoo2013** [comment]
同问啊 我也遇到此问题了

**Comment by xuuhaoo** [comment]
国际通用协议的定制是必须包含,固定长度的报文头,和非定长度的报文体.如果非标准协议框架不予支持.

另外框架没有字符是禁止的.不会出现0xff就断开的情况发生,-1断开的情况是因为服务器断开了此次输出流.也可能是关闭了socket通道.
