### ISSUE TITLE
作为客户端连接时，会自动以IPV6方式连接服务器，发送数据失败

### ISSUE THREAD

**Issue by bbdlg** [xuuhaoo/OkSocket#95]
客户端：android4.4，创建热点xxx，IP为192.168.43.1
服务器：红米note4X，连接xxx，自定义IP为192.168.43.2，开启服务端口1234

客户端连接服务器，用netstat -an|grep 1234 查看，会出现下列连接，但发送数据失败，isConnect()返回false。
#netstat -an|grep 1234                                   
tcp6       0      0 ::ffff:192.168.43.1:49889 ::ffff:192.168.43.2:1234 ESTABLISHED

奇怪的是，上述情况只有在客户端没有插入sim卡时会出现，插入sim卡并启动数据网络后，会正常连接（IPV4）。

尝试禁用客户端的IPV6，没有找到合适的办法，望大神指教:)

**Comment by bbdlg** [comment]
在客户端通过 nc 192.168.43.2 1234 连接服务器，没有出现IPV6的情况。

**Comment by xuuhaoo** [comment]
你上网查查吧.没有插入sim卡的时候android好像是有特殊处理.具体的记不清楚了.
